version: "3.8"

services:
  nest-app:
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: sample
    ports:
      - "3001:3001"
    build: .
    # volumes:
    #   - type: bind
    #     source: ./src
    #     target: /user/src/app
    # depends_on:
    #   - db
  db:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      # MYSQL_USER: user
      # MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/mysql
    image: mysql:8.4.0
volumes:
  db-volume:
